name: teste CI

on:
  push:
    branches:
      - feature/ci

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout projeto de testes
        uses: actions/checkout@v4

      - name: Checkout Hub de Leitura
        uses: actions/checkout@v4
        with:
          repository: GuilhermeFalcoLemos/hub-de-leitura-integrado
          path: hub-de-leitura-integrado

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Instalar dependências do Hub
        working-directory: hub-de-leitura-integrado
        run: npm ci

      - name: Instalar dependências dos testes
        run: npm ci

      - name: Iniciar Hub de Leitura
        working-directory: hub-de-leitura-integrado
        run: npm start &

      - name: Aguardar aplicação
        run: npx wait-on http://localhost:3000

      - name: Executar testes e gerar relatório
        run: npm run test:report

      - name: Verificar relatório
        if: always()
        run: |
          echo "Conteúdo do mochawesome-report:"
          ls -la mochawesome-report || true

      - name: Upload do relatório
        if: success()
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./mochawesome-report

      - name: Publicar no GitHub Pages
        if: success()
        id: deployment
        uses: actions/deploy-pages@v4