name: teste  CI

on:
  push:
    branches: [ feature/ci ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout projeto de testes
        uses: actions/checkout@v4

      - name: Checkout aplicação
        uses: actions/checkout@v4
        with:
          repository: GuilhermeFalcoLemos/hub-de-leitura-integrado
          path: hub-de-leitura-integrado

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies da aplicação
        working-directory: hub-de-leitura-integrado
        run: npm ci

      - name: Install dependencies dos testes
        run: npm ci

      - name: Run Cypress
        uses: cypress-io/github-action@v6
        continue-on-error: true
        with:
          install: false
          browser: chrome
          start: cd hub-de-leitura-integrado && npm start
          wait-on: http://localhost:3000
          wait-on-timeout: 120

      - name: Generate Mochawesome report
        if: always()
        run: |
          npx mochawesome-merge "mochawesome-report/*.json" -o mochawesome-report/mochawesome.json
          npx marge mochawesome-report/mochawesome.json -o mochawesome-report -f index

      - name: Publish Report
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./mochawesome-report